'use client';

import { useState, useEffect } from 'react';
import { Upload, Flame, Award, RefreshCw, Share2, Trophy, Users } from 'lucide-react';
import confetti from 'canvas-confetti';
import { Toaster, toast } from 'sonner';

interface Result {
  score: number;
  label: string;
  wowComment: string;
  archetype: string;
  risk: string;
  celebrityTwin: string;
  dateability: number;
  memeEnergy: string;
  badge: string;
  isPolished: boolean;
}

export default function VibeVerify() {
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<Result | null>(null);
  const [streak, setStreak] = useState(1);
  const [liveUsers] = useState(67);
  const [showLeaderboard, setShowLeaderboard] = useState(false);
  const [animatedScore, setAnimatedScore] = useState(0);

  useEffect(() => {
    const saved = localStorage.getItem('vibeStreak');
    const last = localStorage.getItem('vibeLastDate');
    const today = new Date().toISOString().split('T')[0];
    if (last === today && saved) setStreak(parseInt(saved));
    else if (last) setStreak(2);
  }, []);

  const saveStreak = () => {
    const today = new Date().toISOString().split('T')[0];
    localStorage.setItem('vibeStreak', (streak + 1).toString());
    localStorage.setItem('vibeLastDate', today);
    setStreak(s => s + 1);
  };

  const detectMetadata = async (file: File): Promise<boolean> => {
    const buffer = await file.arrayBuffer();
    const text = new TextDecoder().decode(new Uint8Array(buffer).slice(0, 150000));
    return /c2pa|contentauth|content credentials|dall-e|midjourney|firefly|adobe|generated by|stable diffusion/i.test(text.toLowerCase());
  };

  const vibeCheck = async () => {
    if (!file) return;
    setLoading(true);
    setResult(null);
    setAnimatedScore(0);

    let finalScore = 88;
    let isReal = true;
    let caption = "professional man in suit";
    let isPolished = false;

    const formData = new FormData();
    formData.append('file', file);

    isPolished = await detectMetadata(file);

    try {
      const res = await fetch(
        'https://api-inference.huggingface.co/models/dima806/ai_vs_real_image_detection',
        { method: 'POST', headers: { Authorization: `Bearer ${process.env.NEXT_PUBLIC_HF_TOKEN}` }, body: formData }
      );
      if (res.ok) {
        const data = await res.json();
        const realItem = data.find((item: any) => item.label.toLowerCase().includes('real') || item.label === 'real');
        finalScore = Math.round((realItem?.score || 0.88) * 100);
      }
    } catch (_) {
      finalScore = 82;
    }

    if (isPolished) {
      finalScore = Math.max(42, finalScore - 30);
      isReal = false;
    } else {
      isReal = finalScore > 65;
    }

    let data: any = {};
    try {
      const groqRes = await fetch('/api/groq-comment', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ percentage: finalScore, isReal, caption }),
      });
      data = await groqRes.json();
    } catch (_) {
      data = { wowComment: "This energy is illegally attractive 🔥", archetype: "Main Character Energy", risk: "Zero risk", celebrityTwin: "Idris Elba / Michael B. Jordan vibes", dateability: 96, memeEnergy: "Serving CEO in a rom-com realness", badge: "✅ SAFE TO SLIDE" };
    }

    const newResult: Result = {
      score: finalScore,
      label: isPolished ? 'AI POLISHED / ENHANCED 👀' : (isReal ? 'REAL HUMAN VIBES 🔥' : 'AI / SYNTHETIC DETECTED'),
      wowComment: data.wowComment,
      archetype: data.archetype,
      risk: data.risk,
      celebrityTwin: data.celebrityTwin,
      dateability: data.dateability,
      memeEnergy: data.memeEnergy,
      badge: data.badge,
      isPolished
    };

    setResult(newResult);
    saveStreak();

    let current = 0;
    const timer = setInterval(() => {
      current += Math.ceil((finalScore - current) / 6);
      if (current >= finalScore) { current = finalScore; clearInterval(timer); }
      setAnimatedScore(current);
    }, 35);

    if (isReal && finalScore > 80) confetti({ particleCount: 500, spread: 100 });
    toast(isPolished ? "AI polish detected" : (isReal ? "VIBE APPROVED 💚" : "Synthetic energy detected"));

    setLoading(false);
  };

  const newCheck = () => {
    setFile(null);
    setPreview('');
    setResult(null);
    setAnimatedScore(0);
  };

  const shareBadge = () => {
    if (!result) return;
    const text = `${result.wowComment}\n${result.archetype} • ${result.celebrityTwin}\nDateability ${result.dateability}% 🔥\nGot ${result.score}% real on VibeVerify → https://vibe-verify-ai.vercel.app`;
    navigator.clipboard.writeText(text);
    toast.success("Copied — post this and get the likes 🔥");
  };

  return (
    <div className="min-h-screen bg-zinc-950 text-white overflow-hidden">
      <Toaster position="top-center" richColors />

      <header className="fixed w-full border-b border-purple-500/20 bg-zinc-900/80 backdrop-blur-xl z-50">
        <div className="max-w-5xl mx-auto px-6 py-4 flex justify-between items-center">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 bg-gradient-to-br from-purple-500 to-fuchsia-500 rounded-2xl flex items-center justify-center text-3xl">🔍</div>
            <div>
              <div className="font-bold text-3xl tracking-tighter">VibeVerify</div>
              <div className="text-xs text-purple-400 -mt-1">2026 Reality Layer</div>
            </div>
          </div>
          <div className="flex items-center gap-6">
            <div className="flex items-center gap-1.5 text-sm"><Users className="text-emerald-400" /> {liveUsers} vibing now</div>
            <button onClick={() => setShowLeaderboard(true)} className="flex items-center gap-2 px-5 py-2 bg-white/10 hover:bg-white/20 rounded-full text-sm"><Trophy className="w-4 h-4" /> Leaderboard</button>
            <div className="flex items-center gap-1.5 text-sm"><Flame className="text-orange-400" /> {streak} day streak</div>
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto pt-28 px-6 pb-24">
        <div className="text-center mb-12">
          <div className="inline bg-purple-500/10 text-purple-400 px-5 py-1 rounded-full text-sm mb-4">Global • TerraCode Convergence 2026</div>
          <h1 className="text-7xl font-black tracking-tighter mb-4">See the real vibe.<br />Before you connect.</h1>
          <p className="text-xl text-zinc-400">Catches polished AI + gives the funniest personality roast</p>
        </div>

        <div onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); const f = e.dataTransfer.files[0]; if (f) { setFile(f); setPreview(URL.createObjectURL(f)); setResult(null); } }} className="border-4 border-dashed border-purple-500/30 hover:border-purple-500 rounded-3xl p-20 text-center transition-all bg-zinc-900/50">
          {preview ? (
            <div className="space-y-8">
              <img src={preview} className="mx-auto max-h-96 rounded-3xl shadow-2xl" alt="preview" />
              <button onClick={vibeCheck} disabled={loading} className="w-full max-w-md mx-auto py-7 text-2xl font-bold rounded-2xl bg-gradient-to-r from-purple-600 to-fuchsia-600 hover:scale-105 transition disabled:opacity-70 flex items-center justify-center gap-3">
                {loading ? <>Reading your soul... <RefreshCw className="animate-spin w-7 h-7" /></> : 'RUN VIBE CHECK 🔥'}
              </button>
            </div>
          ) : (
            <label className="cursor-pointer block">
              <div className="mx-auto w-28 h-28 bg-purple-500/10 rounded-3xl flex items-center justify-center mb-8">
                <Upload className="w-14 h-14 text-purple-400" />
              </div>
              <p className="text-4xl font-medium mb-4">Drop any selfie or pic</p>
              <div className="bg-white text-black font-semibold px-12 py-5 rounded-2xl inline-block hover:bg-white/90">Choose from device</div>
              <input type="file" accept="image/*" className="hidden" onChange={e => e.target.files?.[0] && (setFile(e.target.files[0]), setPreview(URL.createObjectURL(e.target.files[0])), setResult(null))} />
            </label>
          )}
        </div>

        {result && (
          <div className="mt-16 max-w-lg mx-auto bg-zinc-900 border border-purple-500/30 rounded-3xl p-10 text-center">
            <div className="text-8xl font-black text-transparent bg-clip-text bg-gradient-to-br from-purple-400 to-fuchsia-400 mb-1">
              {animatedScore}%
            </div>
            <div className="text-3xl font-bold my-4">{result.label}</div>
            {result.isPolished && <div className="text-amber-400 text-sm mb-4">⚠️ AI polish + metadata detected</div>}

            <div className="text-2xl italic mb-8 text-purple-300">"{result.wowComment}"</div>

            <div className="grid grid-cols-2 gap-6 text-left mb-8">
              <div><span className="text-purple-400">Archetype</span><br />{result.archetype}</div>
              <div><span className="text-purple-400">Celeb Twin</span><br />{result.celebrityTwin}</div>
              <div><span className="text-purple-400">Dateability</span><br />{result.dateability}%</div>
              <div><span className="text-purple-400">Meme Energy</span><br />{result.memeEnergy}</div>
            </div>

            <div className="uppercase tracking-[3px] text-sm text-purple-400 mb-8">{result.badge}</div>

            <div className="flex gap-4">
              <button onClick={shareBadge} className="flex-1 py-4 bg-white/10 hover:bg-white/20 rounded-2xl flex items-center justify-center gap-3 font-medium">
                <Share2 className="w-5 h-5" /> Share My Vibe Card
              </button>
              <button onClick={newCheck} className="flex-1 py-4 bg-purple-600 hover:bg-purple-700 rounded-2xl font-medium flex items-center justify-center gap-2">
                <RefreshCw className="w-5 h-5" /> New Pic
              </button>
            </div>
          </div>
        )}
      </main>

      {showLeaderboard && (
        <div className="fixed inset-0 bg-black/90 z-[100] flex items-center justify-center p-6" onClick={() => setShowLeaderboard(false)}>
          <div className="bg-zinc-900 rounded-3xl max-w-md w-full p-8" onClick={e => e.stopPropagation()}>
            <div className="flex items-center gap-3 mb-8"><Trophy className="text-yellow-400" /><span className="text-3xl font-bold">Top Vibers Today</span></div>
            {[{name:"Alex Rivera",score:98},{name:"Sam Kim",score:96},{name:"Jordan Lee",score:95}].map((e,i) => (
              <div key={i} className="flex justify-between py-4 border-b border-white/10"><div>#{i+1} {e.name}</div><div className="text-emerald-400 font-bold">{e.score}%</div></div>
            ))}
            <button onClick={() => setShowLeaderboard(false)} className="mt-8 w-full py-4 text-sm uppercase tracking-widest hover:bg-white/10 rounded-2xl">Close</button>
          </div>
        </div>
      )}

      <footer className="text-center text-xs text-zinc-500 py-12">
        Built live for TerraCode Convergence 2026 • The fun reality check everyone wants to use
      </footer>
    </div>
  );
}